# Generated by Django 5.1.5 on 2025-01-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WillDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('executor_name', models.CharField(max_length=255)),
                ('wife_name', models.CharField(max_length=255)),
                ('child_name_1', models.CharField(max_length=255)),
                ('child_name_2', models.CharField(max_length=255)),
                ('flat_no', models.CharField(max_length=50)),
                ('flat_address', models.TextField()),
                ('date', models.CharField(max_length=50)),
                ('month', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
            ],
        ),
    ]
