# Generated by Django 5.1.5 on 2025-01-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('will', 'Simple Will'), ('license', 'License Agreement')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField()),
                ('executor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('wife_name', models.CharField(blank=True, max_length=255, null=True)),
                ('child_name_1', models.CharField(blank=True, max_length=255, null=True)),
                ('child_name_2', models.CharField(blank=True, max_length=255, null=True)),
                ('flat_no', models.CharField(blank=True, max_length=50, null=True)),
                ('flat_address', models.TextField(blank=True, null=True)),
                ('date', models.CharField(max_length=50)),
                ('month', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.CharField(blank=True, max_length=50, null=True)),
                ('time', models.CharField(blank=True, max_length=50, null=True)),
                ('generated_file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='WillDocument',
        ),
    ]
