# Generated by Django 5.1.5 on 2025-03-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_legaldocument_advance_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaldocument',
            name='accused_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='accused_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='appearing_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='appearing_month',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='appearing_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='bail_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='name_of_appearing_court',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='name_of_issuing_court',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='name_of_surety_court',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='name_of_trial_court',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='offense',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='present_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='present_month',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='present_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='surety_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='surety_bail_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='surety_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='trial_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='trial_month',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='trial_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
