# Generated by Django 5.1.5 on 2025-03-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_legaldocument_interest_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaldocument',
            name='compensation_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='employee_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='employee_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='employee_qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='employer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='non_compete_duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='penalty_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='restricted_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='specific_product',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='trade_secret_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='type_of_product',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='document_type',
            field=models.CharField(choices=[('will', 'Simple Will'), ('license', 'License Agreement'), ('loan_agreement', 'Loan Agreement'), ('deed_of_hypothecation', 'Deed Of Hypothecation'), ('contract_bond', 'Contract Bond'), ('simple_money_bond', 'Simple Money Bond'), ('employee_bond_for_non_compete', 'Employee Bond for Non-Compete')], max_length=255),
        ),
    ]
