# Generated by Django 5.1.5 on 2025-03-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_legaldocument_business_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaldocument',
            name='date',
            field=models.DateField(),
        ),
    ]
