# Generated by Django 5.1.5 on 2025-03-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_legaldocument_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaldocument',
            name='donee_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='donee_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='donor_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='donor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='donor_relationship_to_donee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='property_market_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='document_type',
            field=models.CharField(choices=[('will', 'Simple Will'), ('license', 'License Agreement'), ('loan_agreement', 'Loan Agreement'), ('deed_of_hypothecation', 'Deed Of Hypothecation'), ('contract_bond', 'Contract Bond'), ('simple_money_bond', 'Simple Money Bond'), ('employee_bond_for_non_compete', 'Employee Bond for Non-Compete'), ('simple_mortgage_deed', 'Simple Mortgage Deed'), ('rent_agreement', 'Rent Agreement (For a term of years)'), ('sale_agreement', 'Agreement For Sale'), ('anticipatory_bail_petition_format', 'Anticipatory Bail Petition Format'), ('deed_of_adoption', 'Deed Of Adoption'), ('leave_and_license_agreement', 'Leave and License Agreement'), ('partnership_deed', 'Partnership Deed'), ('deed_of_gift_of_immovable_property', 'Deed of Gift of Immovable Property')], max_length=255),
        ),
    ]
