# Generated by Django 5.1.5 on 2025-03-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_legaldocument_allocated_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaldocument',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='first_child_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='first_child_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='husband_father_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='husband_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='husband_residence_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='husband_visiting_time_end',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='husband_visiting_time_start',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='maintenance_amount_from_husband',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='second_child_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='second_child_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='document_type',
            field=models.CharField(choices=[('will', 'Simple Will'), ('license', 'License Agreement'), ('loan_agreement', 'Loan Agreement'), ('deed_of_hypothecation', 'Deed Of Hypothecation'), ('contract_bond', 'Contract Bond'), ('simple_money_bond', 'Simple Money Bond'), ('employee_bond_for_non_compete', 'Employee Bond for Non-Compete'), ('simple_mortgage_deed', 'Simple Mortgage Deed'), ('rent_agreement', 'Rent Agreement (For a term of years)'), ('sale_agreement', 'Agreement For Sale'), ('anticipatory_bail_petition_format', 'Anticipatory Bail Petition Format'), ('deed_of_adoption', 'Deed Of Adoption'), ('leave_and_license_agreement', 'Leave and License Agreement'), ('partnership_deed', 'Partnership Deed'), ('deed_of_gift_of_immovable_property', 'Deed of Gift of Immovable Property'), ('memorandum_recording_family_settlement', 'Memorandum Recording Family Settlement'), ('partition_deed', 'Partition Deed'), ('separation_agreement', 'Separation Agreement')], max_length=255),
        ),
    ]
